Patch 3.4 (#482)
* Readded team_name and team_id to raid dts.

* Added 'form_or_empy' dts to raid and pokemon.

* Fixed team_name not working without gym notifications enabled.

* Removed potentially copyrighted material.

* Centralize image link url.

* Fixed a bug with distance matrix calculations.

* Fixed bug for walking and biking as well.

* Adding <team_id> and <team_name> to raid egg notifications (#463)

* Added <lat_5> and <lng_5> DTS.

* Adding (File)Caching  (#465)

* Added Cache interface.

* Implimented in-memory cache.

* Added FileCache.

* Graceful exiting and other fixes

* Switched FileCache r/w to binary mode for windows.

* Fixed bug with first time gyms getting reject with wrong error message.

* Fix bad format syntax (#470)

Resolves AttributeError: 'float' object has no attribute '5f'

* Bug fixes for Caching

* Use "Egg" instead of "Raid" in process_egg log message (#473)

* Fix egg expire time (#474)

* Fix FileCache not getting cleaned (#472)

* Fixed FileCache not getting cleaned

...plus some typos and a smaller clean_hist function

* Do not shadow built in variables

* Applied nitpick-fixes ;)

* Min max catchable cp (#438)

* Reworked Locale translations and added form DTS.

* Location Services rework - Loc DTS now cache and returns results in set language.

*  Add support for minimum and maximum catchable CP DTS for raid pkmn

* Add a flipping pokedex full of information in the base_stats
Generalize raid CP range by calculating it based on pokemon stats
Reformat the Utils file so code style is consistent

* root path is unset on manager process

* Update base stats for Ho-Oh

* Delete unused cp_range-file from refactoring into stats

* Update filters.json.example

* Adding `"min_level":"0", "max_level":"30",` to `filters.json.example`

* Updating `raid` filters with new raid bosses

* Updating `filters.json.example` to remove old raid bosses

* Fix README (#481)

* Webhook Tester (#479)

* Added initial webhook tester

* Basic Instructions
Included accurate timing for all payloads
Changed a few defaults

* Added menus

* Added initial webhook tester

* Basic Instructions
Included accurate timing for all payloads
Changed a few defaults

* Added menus

* Added 'pkmn_id_3' and 'form_id_3' DTS

* Added 'pkmn_id_3' and 'form_id_or_empty' to Raids DTS.

* Updated image urls.

* Update RM Webhook(#469)

* Updating Webhook-Structs for Pokemon

* Fixing Pokemon Webhook Structs

* Removing points from gym webhook

* Updating Webhook Standards to fix for Monocole

The added standards are not provided by Monocole, so fixing the data gathering mechanism.